2020-04-27 04:44:52,709 INFO client.RMProxy: Connecting to ResourceManager at /192.168.122.238:8032
2020-04-27 04:44:53,086 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2020-04-27 04:44:53,110 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/ubuntu/.staging/job_1587951704827_0003
2020-04-27 04:44:53,226 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2020-04-27 04:44:53,368 INFO input.FileInputFormat: Total input files to process : 1
2020-04-27 04:44:53,416 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2020-04-27 04:44:53,662 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2020-04-27 04:44:53,678 INFO mapreduce.JobSubmitter: number of splits:15
2020-04-27 04:44:53,826 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2020-04-27 04:44:53,841 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1587951704827_0003
2020-04-27 04:44:53,841 INFO mapreduce.JobSubmitter: Executing with tokens: []
2020-04-27 04:44:53,986 INFO conf.Configuration: resource-types.xml not found
2020-04-27 04:44:53,986 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
2020-04-27 04:44:54,074 INFO impl.YarnClientImpl: Submitted application application_1587951704827_0003
2020-04-27 04:44:54,107 INFO mapreduce.Job: The url to track the job: http://namenode1.local:8088/proxy/application_1587951704827_0003/
2020-04-27 04:44:54,107 INFO mapreduce.Job: Running job: job_1587951704827_0003
2020-04-27 04:44:59,247 INFO mapreduce.Job: Job job_1587951704827_0003 running in uber mode : false
2020-04-27 04:44:59,249 INFO mapreduce.Job:  map 0% reduce 0%
2020-04-27 04:45:00,322 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000006_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000008 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,353 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000003_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000005 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,357 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000000_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000002 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,363 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000007_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000009 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,366 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000004_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000006 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,369 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000005_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000007 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,373 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000002_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000004 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:00,376 INFO mapreduce.Job: Task Id : attempt_1587951704827_0003_m_000001_0, Status : FAILED
Container launch failed for container_1587951704827_0003_01_000003 : java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode1.local
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:447)
	at org.apache.hadoop.security.SecurityUtil.setTokenService(SecurityUtil.java:425)
	at org.apache.hadoop.yarn.util.ConverterUtils.convertFromYarn(ConverterUtils.java:184)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.newProxy(ContainerManagementProtocolProxy.java:277)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy$ContainerManagementProtocolProxyData.<init>(ContainerManagementProtocolProxy.java:252)
	at org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy.getProxy(ContainerManagementProtocolProxy.java:137)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl.getCMProxy(ContainerLauncherImpl.java:433)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:146)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: namenode1.local
	... 12 more

2020-04-27 04:45:09,461 INFO mapreduce.Job:  map 7% reduce 0%
2020-04-27 04:45:10,469 INFO mapreduce.Job:  map 20% reduce 0%
2020-04-27 04:45:11,482 INFO mapreduce.Job:  map 33% reduce 0%
2020-04-27 04:45:12,489 INFO mapreduce.Job:  map 53% reduce 0%
2020-04-27 04:45:13,496 INFO mapreduce.Job:  map 80% reduce 0%
2020-04-27 04:45:14,506 INFO mapreduce.Job:  map 87% reduce 0%
2020-04-27 04:45:15,518 INFO mapreduce.Job:  map 100% reduce 0%
2020-04-27 04:45:26,623 INFO mapreduce.Job:  map 100% reduce 84%
2020-04-27 04:45:30,662 INFO mapreduce.Job:  map 100% reduce 100%
2020-04-27 04:45:30,679 INFO mapreduce.Job: Job job_1587951704827_0003 completed successfully
2020-04-27 04:45:30,836 INFO mapreduce.Job: Counters: 58
	File System Counters
		FILE: Number of bytes read=1020000018
		FILE: Number of bytes written=2043616794
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=1001836793
		HDFS: Number of bytes written=1000000000
		HDFS: Number of read operations=50
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=2
		HDFS: Number of bytes read erasure-coded=0
	Job Counters 
		Failed map tasks=8
		Killed map tasks=1
		Launched map tasks=24
		Launched reduce tasks=1
		Other local map tasks=9
		Data-local map tasks=8
		Rack-local map tasks=7
		Total time spent by all maps in occupied slots (ms)=117667
		Total time spent by all reduces in occupied slots (ms)=17753
		Total time spent by all map tasks (ms)=117667
		Total time spent by all reduce tasks (ms)=17753
		Total vcore-milliseconds taken by all map tasks=117667
		Total vcore-milliseconds taken by all reduce tasks=17753
		Total megabyte-milliseconds taken by all map tasks=120491008
		Total megabyte-milliseconds taken by all reduce tasks=18179072
	Map-Reduce Framework
		Map input records=10000000
		Map output records=10000000
		Map output bytes=1000000000
		Map output materialized bytes=1020000090
		Input split bytes=1785
		Combine input records=10000000
		Combine output records=10000000
		Reduce input groups=10000000
		Reduce shuffle bytes=1020000090
		Reduce input records=10000000
		Reduce output records=10000000
		Spilled Records=20000000
		Shuffled Maps =15
		Failed Shuffles=0
		Merged Map outputs=15
		GC time elapsed (ms)=2362
		CPU time spent (ms)=80740
		Physical memory (bytes) snapshot=6214590464
		Virtual memory (bytes) snapshot=41506652160
		Total committed heap usage (bytes)=6425673728
		Peak Map Physical memory (bytes)=479883264
		Peak Map Virtual memory (bytes)=2595348480
		Peak Reduce Physical memory (bytes)=764362752
		Peak Reduce Virtual memory (bytes)=2601607168
	Shuffle Errors
		BAD_ID=0
		CONNECTION=0
		IO_ERROR=0
		WRONG_LENGTH=0
		WRONG_MAP=0
		WRONG_REDUCE=0
	File Input Format Counters 
		Bytes Read=1001835008
	File Output Format Counters 
		Bytes Written=1000000000

real	0m39.648s
user	0m5.720s
sys	0m0.497s
